const FLASHCARDS = [
  { mk: "Здраво", en: "Hello", phonetic: "", category: "phrases" },
  { mk: "Ало", en: "Hello (on phone)", phonetic: "", category: "phrases" },
  { mk: "Добро утро", en: "Good morning", phonetic: "", category: "phrases" },
  { mk: "Добар ден", en: "Good afternoon", phonetic: "", category: "phrases" },
  { mk: "Добра вечер", en: "Good evening", phonetic: "", category: "phrases" },
  { mk: "Добра ноќ", en: "Good night", phonetic: "", category: "phrases" },
  { mk: "Добредојде", en: "Welcome", phonetic: "", category: "phrases" },
  { mk: "Како си?", en: "How are you? (informal)", phonetic: "", category: "phrases" },
  { mk: "Како сте?", en: "How are you? (formal)", phonetic: "", category: "phrases" },
  { mk: "Добро сум, благодарам", en: "I am fine, thank you", phonetic: "", category: "phrases" },
  { mk: "Како се викаш?", en: "What is your name? (informal)", phonetic: "", category: "phrases" },
  { mk: "Како се викате?", en: "What is your name? (formal)", phonetic: "", category: "phrases" },
  { mk: "Јас се викам...", en: "My name is...", phonetic: "", category: "phrases" },
  { mk: "Моето име е...", en: "My name is...", phonetic: "", category: "phrases" },
  { mk: "Од каде си?", en: "Where are you from? (informal)", phonetic: "", category: "phrases" },
  { mk: "Мило ми е што те запознав", en: "Nice to meet you", phonetic: "", category: "phrases" },
  { mk: "Довидување", en: "Goodbye", phonetic: "", category: "phrases" },
  { mk: "Пријатно", en: "Goodbye / take care", phonetic: "", category: "phrases" },
  { mk: "Благодарам", en: "Thank you", phonetic: "", category: "phrases" },
  { mk: "Ви благодарам", en: "Thank you (formal)", phonetic: "", category: "phrases" },
  { mk: "Фала", en: "Thanks (informal)", phonetic: "", category: "phrases" },
  { mk: "Молам", en: "You are welcome", phonetic: "", category: "phrases" },
  { mk: "Ве молам", en: "Please (formal)", phonetic: "", category: "phrases" },
  { mk: "Извини", en: "Sorry (informal)", phonetic: "", category: "phrases" },
  { mk: "Извинете", en: "Excuse me / sorry (formal)", phonetic: "", category: "phrases" },
  { mk: "Не знам", en: "I do not know", phonetic: "", category: "phrases" },
  { mk: "Разбирам", en: "I understand", phonetic: "", category: "phrases" },
  { mk: "Не разбирам", en: "I do not understand", phonetic: "", category: "phrases" },
  { mk: "Ве молам повторете", en: "Please repeat", phonetic: "", category: "phrases" },
  { mk: "Како се вели... на македонски?", en: "How do you say... in Macedonian?", phonetic: "", category: "phrases" },
  { mk: "Дали зборувате македонски?", en: "Do you speak Macedonian?", phonetic: "", category: "phrases" },
  { mk: "Дали зборувате англиски?", en: "Do you speak English?", phonetic: "", category: "phrases" },
  { mk: "Да, малку", en: "Yes, a little", phonetic: "", category: "phrases" },
  { mk: "Учам македонски", en: "I am learning Macedonian", phonetic: "", category: "phrases" },
  { mk: "Колку чини ова?", en: "How much is this?", phonetic: "", category: "phrases" },
  { mk: "Колку кошта?", en: "How much does it cost?", phonetic: "", category: "phrases" },
  { mk: "Каде е...?", en: "Where is...?", phonetic: "", category: "phrases" },
  { mk: "Каде е тоалетот?", en: "Where is the toilet?", phonetic: "", category: "phrases" },
  { mk: "Нема на што", en: "You are welcome (reply)", phonetic: "", category: "phrases" },
  { mk: "Нема проблем", en: "No problem", phonetic: "", category: "phrases" },
  { mk: "Со среќа!", en: "Good luck!", phonetic: "", category: "phrases" },
  { mk: "Наздравје!", en: "Cheers!", phonetic: "", category: "phrases" },
  { mk: "Пријатен ден", en: "Have a nice day", phonetic: "", category: "phrases" },
  { mk: "Пријатно јадење", en: "Bon appetit", phonetic: "", category: "phrases" },
  { mk: "Те сакам", en: "I love you", phonetic: "", category: "phrases" },
  { mk: "Ми недостасуваш", en: "I miss you", phonetic: "", category: "phrases" },
  { mk: "Помош!", en: "Help!", phonetic: "", category: "phrases" },
  { mk: "Стоп!", en: "Stop!", phonetic: "", category: "phrases" },
  { mk: "Оди лево", en: "Go left", phonetic: "", category: "phrases" },
  { mk: "Оди десно", en: "Go right", phonetic: "", category: "phrases" },
  { mk: "Оди право", en: "Go straight", phonetic: "", category: "phrases" },
  { mk: "Зборувај побавно", en: "Speak slowly", phonetic: "", category: "phrases" },
  { mk: "Колку е часот?", en: "What time is it?", phonetic: "", category: "phrases" },
  { mk: "Среќен роденден", en: "Happy birthday", phonetic: "", category: "phrases" },
  { mk: "Среќна Нова година", en: "Happy New Year", phonetic: "", category: "phrases" },
  { mk: "Честитки!", en: "Congratulations!", phonetic: "", category: "phrases" },
  { mk: "Те сакам многу", en: "I love you very much", phonetic: "", category: "phrases" },
  { mk: "Мислам на тебе", en: "I am thinking of you", phonetic: "", category: "phrases" },
  { mk: "Убава си", en: "You are beautiful (to a woman)", phonetic: "", category: "phrases" },
  { mk: "Убав си", en: "You are handsome (to a man)", phonetic: "", category: "phrases" },
  { mk: "Гушни ме", en: "Hug me", phonetic: "", category: "phrases" },
  { mk: "Поцелувај ме", en: "Kiss me", phonetic: "", category: "phrases" },
  { mk: "Добро ми е со тебе", en: "I feel good with you", phonetic: "", category: "phrases" },
  { mk: "За тебе", en: "For you", phonetic: "", category: "phrases" },
  { mk: "Со љубов", en: "With love", phonetic: "", category: "phrases" },
  { mk: "Гладен сум", en: "I am hungry (male)", phonetic: "", category: "phrases" },
  { mk: "Гладна сум", en: "I am hungry (female)", phonetic: "", category: "phrases" },
  { mk: "Жеден сум", en: "I am thirsty (male)", phonetic: "", category: "phrases" },
  { mk: "Жедна сум", en: "I am thirsty (female)", phonetic: "", category: "phrases" },
  { mk: "Уморен сум", en: "I am tired (male)", phonetic: "", category: "phrases" },
  { mk: "Уморна сум", en: "I am tired (female)", phonetic: "", category: "phrases" },
  { mk: "Ми се допаѓа", en: "I like it", phonetic: "", category: "phrases" },
  { mk: "Можеш ли да повториш?", en: "Can you repeat that?", phonetic: "", category: "phrases" },
  { mk: "Во ред", en: "OK / all right", phonetic: "", category: "phrases" },
  { mk: "Јас сум од...", en: "I am from...", phonetic: "", category: "phrases" },
  { mk: "Оздрави брзо", en: "Get well soon", phonetic: "", category: "phrases" },
  { mk: "На здравје!", en: "Bless you! / To your health!", phonetic: "", category: "phrases" },
  { mk: "Остави ме на мир", en: "Leave me alone", phonetic: "", category: "phrases" },
  { mk: "Повикајте полиција!", en: "Call the police!", phonetic: "", category: "phrases" },
  { mk: "Ми треба доктор", en: "I need a doctor", phonetic: "", category: "phrases" },
  { mk: "Јас не разбирам", en: "I do not understand", phonetic: "", category: "phrases" },
  { mk: "Зборувајте побавно", en: "Speak more slowly (formal)", phonetic: "", category: "phrases" },
  { mk: "Еден", en: "One", phonetic: "", category: "numbers" },
  { mk: "Една", en: "One (feminine)", phonetic: "", category: "numbers" },
  { mk: "Едно", en: "One (neuter)", phonetic: "", category: "numbers" },
  { mk: "Два", en: "Two (masculine)", phonetic: "", category: "numbers" },
  { mk: "Две", en: "Two (feminine/neuter)", phonetic: "", category: "numbers" },
  { mk: "Три", en: "Three", phonetic: "", category: "numbers" },
  { mk: "Четири", en: "Four", phonetic: "", category: "numbers" },
  { mk: "Пет", en: "Five", phonetic: "", category: "numbers" },
  { mk: "Шест", en: "Six", phonetic: "", category: "numbers" },
  { mk: "Седум", en: "Seven", phonetic: "", category: "numbers" },
  { mk: "Осум", en: "Eight", phonetic: "", category: "numbers" },
  { mk: "Девет", en: "Nine", phonetic: "", category: "numbers" },
  { mk: "Десет", en: "Ten", phonetic: "", category: "numbers" },
  { mk: "Единадесет", en: "Eleven", phonetic: "", category: "numbers" },
  { mk: "Дванадесет", en: "Twelve", phonetic: "", category: "numbers" },
  { mk: "Тринаесет", en: "Thirteen", phonetic: "", category: "numbers" },
  { mk: "Четиринаесет", en: "Fourteen", phonetic: "", category: "numbers" },
  { mk: "Петнаесет", en: "Fifteen", phonetic: "", category: "numbers" },
  { mk: "Дваесет", en: "Twenty", phonetic: "", category: "numbers" },
  { mk: "Триесет", en: "Thirty", phonetic: "", category: "numbers" },
  { mk: "Педесет", en: "Fifty", phonetic: "", category: "numbers" },
  { mk: "Сто", en: "One hundred", phonetic: "", category: "numbers" },
  { mk: "Илјада", en: "One thousand", phonetic: "", category: "numbers" },
  { mk: "Јас", en: "I", phonetic: "", category: "words" },
  { mk: "Ти", en: "You (informal)", phonetic: "", category: "words" },
  { mk: "Тој", en: "He", phonetic: "", category: "words" },
  { mk: "Таа", en: "She", phonetic: "", category: "words" },
  { mk: "Тие", en: "They", phonetic: "", category: "words" },
  { mk: "Ние", en: "We", phonetic: "", category: "words" },
  { mk: "Вие", en: "You (formal/plural)", phonetic: "", category: "words" },
  { mk: "Да", en: "Yes", phonetic: "", category: "words" },
  { mk: "Не", en: "No", phonetic: "", category: "words" },
  { mk: "Можеби", en: "Maybe", phonetic: "", category: "words" },
  { mk: "Секогаш", en: "Always", phonetic: "", category: "words" },
  { mk: "Никогаш", en: "Never", phonetic: "", category: "words" },
  { mk: "Често", en: "Often", phonetic: "", category: "words" },
  { mk: "Понекогаш", en: "Sometimes", phonetic: "", category: "words" },
  { mk: "Уште", en: "Still / yet", phonetic: "", category: "words" },
  { mk: "Веќе", en: "Already", phonetic: "", category: "words" },
  { mk: "Сега", en: "Now", phonetic: "", category: "words" },
  { mk: "Денес", en: "Today", phonetic: "", category: "words" },
  { mk: "Утре", en: "Tomorrow", phonetic: "", category: "words" },
  { mk: "Вчера", en: "Yesterday", phonetic: "", category: "words" },
  { mk: "Подоцна", en: "Later", phonetic: "", category: "words" },
  { mk: "Рано", en: "Early", phonetic: "", category: "words" },
  { mk: "Брзо", en: "Quickly", phonetic: "", category: "words" },
  { mk: "Бавно", en: "Slowly", phonetic: "", category: "words" },
  { mk: "Овде", en: "Here", phonetic: "", category: "words" },
  { mk: "Таму", en: "There", phonetic: "", category: "words" },
  { mk: "Блиску", en: "Near", phonetic: "", category: "words" },
  { mk: "Далеку", en: "Far", phonetic: "", category: "words" },
  { mk: "Лево", en: "Left", phonetic: "", category: "words" },
  { mk: "Десно", en: "Right", phonetic: "", category: "words" },
  { mk: "Горе", en: "Up", phonetic: "", category: "words" },
  { mk: "Долу", en: "Down", phonetic: "", category: "words" },
  { mk: "Добро", en: "Good / well", phonetic: "", category: "words" },
  { mk: "Лошо", en: "Bad", phonetic: "", category: "words" },
  { mk: "Убаво", en: "Beautiful / nice", phonetic: "", category: "words" },
  { mk: "Голем", en: "Big", phonetic: "", category: "words" },
  { mk: "Мал", en: "Small", phonetic: "", category: "words" },
  { mk: "Нов", en: "New", phonetic: "", category: "words" },
  { mk: "Стар", en: "Old", phonetic: "", category: "words" },
  { mk: "Млад", en: "Young", phonetic: "", category: "words" },
  { mk: "Топло", en: "Warm", phonetic: "", category: "words" },
  { mk: "Ладно", en: "Cold", phonetic: "", category: "words" },
  { mk: "Жешко", en: "Hot", phonetic: "", category: "words" },
  { mk: "Бело", en: "White", phonetic: "", category: "words" },
  { mk: "Црно", en: "Black", phonetic: "", category: "words" },
  { mk: "Црвено", en: "Red", phonetic: "", category: "words" },
  { mk: "Сино", en: "Blue", phonetic: "", category: "words" },
  { mk: "Зелено", en: "Green", phonetic: "", category: "words" },
  { mk: "Жолто", en: "Yellow", phonetic: "", category: "words" },
  { mk: "Портокал", en: "Orange", phonetic: "", category: "words" },
  { mk: "Кафеаво", en: "Brown", phonetic: "", category: "words" },
  { mk: "Сиво", en: "Gray", phonetic: "", category: "words" },
  { mk: "Розово", en: "Pink", phonetic: "", category: "words" },
  { mk: "Кафе", en: "Coffee", phonetic: "", category: "words" },
  { mk: "Чај", en: "Tea", phonetic: "", category: "words" },
  { mk: "Сок", en: "Juice", phonetic: "", category: "words" },
  { mk: "Вино", en: "Wine", phonetic: "", category: "words" },
  { mk: "Пиво", en: "Beer", phonetic: "", category: "words" },
  { mk: "Вода", en: "Water", phonetic: "", category: "words" },
  { mk: "Млеко", en: "Milk", phonetic: "", category: "words" },
  { mk: "Леб", en: "Bread", phonetic: "", category: "words" },
  { mk: "Сирење", en: "Cheese", phonetic: "", category: "words" },
  { mk: "Месо", en: "Meat", phonetic: "", category: "words" },
  { mk: "Риба", en: "Fish", phonetic: "", category: "words" },
  { mk: "Јајце", en: "Egg", phonetic: "", category: "words" },
  { mk: "Ориз", en: "Rice", phonetic: "", category: "words" },
  { mk: "Супа", en: "Soup", phonetic: "", category: "words" },
  { mk: "Салата", en: "Salad", phonetic: "", category: "words" },
  { mk: "Јаболко", en: "Apple", phonetic: "", category: "words" },
  { mk: "Банана", en: "Banana", phonetic: "", category: "words" },
  { mk: "Домат", en: "Tomato", phonetic: "", category: "words" },
  { mk: "Компир", en: "Potato", phonetic: "", category: "words" },
  { mk: "Бурек", en: "Burek (pastry)", phonetic: "", category: "words" },
  { mk: "Торта", en: "Cake", phonetic: "", category: "words" },
  { mk: "Шеќер", en: "Sugar", phonetic: "", category: "words" },
  { mk: "Сол", en: "Salt", phonetic: "", category: "words" },
  { mk: "Масло", en: "Oil / butter", phonetic: "", category: "words" },
  { mk: "Мед", en: "Honey", phonetic: "", category: "words" },
  { mk: "Пипер", en: "Pepper", phonetic: "", category: "words" },
  { mk: "Пиле", en: "Chicken", phonetic: "", category: "words" },
  { mk: "Свињско", en: "Pork", phonetic: "", category: "words" },
  { mk: "Говедско", en: "Beef", phonetic: "", category: "words" },
  { mk: "Зеленчук", en: "Vegetables", phonetic: "", category: "words" },
  { mk: "Овошје", en: "Fruit", phonetic: "", category: "words" },
  { mk: "Јадење", en: "Food / meal", phonetic: "", category: "words" },
  { mk: "Пијалок", en: "Drink", phonetic: "", category: "words" },
  { mk: "Мајка", en: "Mother", phonetic: "", category: "words" },
  { mk: "Татко", en: "Father", phonetic: "", category: "words" },
  { mk: "Брат", en: "Brother", phonetic: "", category: "words" },
  { mk: "Сестра", en: "Sister", phonetic: "", category: "words" },
  { mk: "Син", en: "Son", phonetic: "", category: "words" },
  { mk: "Ќерка", en: "Daughter", phonetic: "", category: "words" },
  { mk: "Баба", en: "Grandmother", phonetic: "", category: "words" },
  { mk: "Дедо", en: "Grandfather", phonetic: "", category: "words" },
  { mk: "Маж", en: "Man / husband", phonetic: "", category: "words" },
  { mk: "Жена", en: "Woman / wife", phonetic: "", category: "words" },
  { mk: "Дете", en: "Child", phonetic: "", category: "words" },
  { mk: "Деца", en: "Children", phonetic: "", category: "words" },
  { mk: "Пријател", en: "Friend", phonetic: "", category: "words" },
  { mk: "Пријателка", en: "Friend (female)", phonetic: "", category: "words" },
  { mk: "Семејство", en: "Family", phonetic: "", category: "words" },
  { mk: "Сосед", en: "Neighbor", phonetic: "", category: "words" },
  { mk: "Колега", en: "Colleague", phonetic: "", category: "words" },
  { mk: "Девојка", en: "Girlfriend / girl", phonetic: "", category: "words" },
  { mk: "Момче", en: "Boy / boyfriend", phonetic: "", category: "words" },
  { mk: "Луѓе", en: "People", phonetic: "", category: "words" },
  { mk: "Човек", en: "Person", phonetic: "", category: "words" },
  { mk: "Доктор", en: "Doctor", phonetic: "", category: "words" },
  { mk: "Учител", en: "Teacher", phonetic: "", category: "words" },
  { mk: "Студент", en: "Student", phonetic: "", category: "words" },
  { mk: "Полицаец", en: "Police officer", phonetic: "", category: "words" },
  { mk: "Глава", en: "Head", phonetic: "", category: "words" },
  { mk: "Коса", en: "Hair", phonetic: "", category: "words" },
  { mk: "Око", en: "Eye", phonetic: "", category: "words" },
  { mk: "Уво", en: "Ear", phonetic: "", category: "words" },
  { mk: "Нос", en: "Nose", phonetic: "", category: "words" },
  { mk: "Уста", en: "Mouth", phonetic: "", category: "words" },
  { mk: "Заб", en: "Tooth", phonetic: "", category: "words" },
  { mk: "Врат", en: "Neck", phonetic: "", category: "words" },
  { mk: "Рамо", en: "Shoulder", phonetic: "", category: "words" },
  { mk: "Рака", en: "Hand / arm", phonetic: "", category: "words" },
  { mk: "Прст", en: "Finger", phonetic: "", category: "words" },
  { mk: "Нога", en: "Leg / foot", phonetic: "", category: "words" },
  { mk: "Срце", en: "Heart", phonetic: "", category: "words" },
  { mk: "Крв", en: "Blood", phonetic: "", category: "words" },
  { mk: "Коска", en: "Bone", phonetic: "", category: "words" },
  { mk: "Кожа", en: "Skin", phonetic: "", category: "words" },
  { mk: "Куќа", en: "House", phonetic: "", category: "words" },
  { mk: "Дом", en: "Home", phonetic: "", category: "words" },
  { mk: "Соба", en: "Room", phonetic: "", category: "words" },
  { mk: "Кујна", en: "Kitchen", phonetic: "", category: "words" },
  { mk: "Спална", en: "Bedroom", phonetic: "", category: "words" },
  { mk: "Бања", en: "Bathroom", phonetic: "", category: "words" },
  { mk: "Врата", en: "Door", phonetic: "", category: "words" },
  { mk: "Прозорец", en: "Window", phonetic: "", category: "words" },
  { mk: "Маса", en: "Table", phonetic: "", category: "words" },
  { mk: "Стол", en: "Chair", phonetic: "", category: "words" },
  { mk: "Кревет", en: "Bed", phonetic: "", category: "words" },
  { mk: "Клуч", en: "Key", phonetic: "", category: "words" },
  { mk: "Телефон", en: "Phone", phonetic: "", category: "words" },
  { mk: "Компјутер", en: "Computer", phonetic: "", category: "words" },
  { mk: "Книга", en: "Book", phonetic: "", category: "words" },
  { mk: "Хартија", en: "Paper", phonetic: "", category: "words" },
  { mk: "Оган", en: "Fire", phonetic: "", category: "words" },
  { mk: "Светло", en: "Light", phonetic: "", category: "words" },
  { mk: "Автомобил", en: "Car", phonetic: "", category: "words" },
  { mk: "Автобус", en: "Bus", phonetic: "", category: "words" },
  { mk: "Воз", en: "Train", phonetic: "", category: "words" },
  { mk: "Авион", en: "Plane", phonetic: "", category: "words" },
  { mk: "Велосипед", en: "Bicycle", phonetic: "", category: "words" },
  { mk: "Мотор", en: "Motorcycle", phonetic: "", category: "words" },
  { mk: "Такси", en: "Taxi", phonetic: "", category: "words" },
  { mk: "Пат", en: "Road / path", phonetic: "", category: "words" },
  { mk: "Улица", en: "Street", phonetic: "", category: "words" },
  { mk: "Град", en: "City", phonetic: "", category: "words" },
  { mk: "Село", en: "Village", phonetic: "", category: "words" },
  { mk: "Држава", en: "Country", phonetic: "", category: "words" },
  { mk: "Свет", en: "World", phonetic: "", category: "words" },
  { mk: "Планина", en: "Mountain", phonetic: "", category: "words" },
  { mk: "Море", en: "Sea", phonetic: "", category: "words" },
  { mk: "Река", en: "River", phonetic: "", category: "words" },
  { mk: "Езеро", en: "Lake", phonetic: "", category: "words" },
  { mk: "Остров", en: "Island", phonetic: "", category: "words" },
  { mk: "Шума", en: "Forest", phonetic: "", category: "words" },
  { mk: "Дрво", en: "Tree", phonetic: "", category: "words" },
  { mk: "Цвет", en: "Flower", phonetic: "", category: "words" },
  { mk: "Трева", en: "Grass", phonetic: "", category: "words" },
  { mk: "Сонце", en: "Sun", phonetic: "", category: "words" },
  { mk: "Месечина", en: "Moon", phonetic: "", category: "words" },
  { mk: "Ѕвезда", en: "Star", phonetic: "", category: "words" },
  { mk: "Небо", en: "Sky", phonetic: "", category: "words" },
  { mk: "Облак", en: "Cloud", phonetic: "", category: "words" },
  { mk: "Дожд", en: "Rain", phonetic: "", category: "words" },
  { mk: "Снег", en: "Snow", phonetic: "", category: "words" },
  { mk: "Ветер", en: "Wind", phonetic: "", category: "words" },
  { mk: "Есен", en: "Autumn", phonetic: "", category: "words" },
  { mk: "Пролет", en: "Spring", phonetic: "", category: "words" },
  { mk: "Лето", en: "Summer", phonetic: "", category: "words" },
  { mk: "Зима", en: "Winter", phonetic: "", category: "words" },
  { mk: "Куче", en: "Dog", phonetic: "", category: "words" },
  { mk: "Мачка", en: "Cat", phonetic: "", category: "words" },
  { mk: "Коњ", en: "Horse", phonetic: "", category: "words" },
  { mk: "Крава", en: "Cow", phonetic: "", category: "words" },
  { mk: "Птица", en: "Bird", phonetic: "", category: "words" },
  { mk: "Мајмун", en: "Monkey", phonetic: "", category: "words" },
  { mk: "Мечка", en: "Bear", phonetic: "", category: "words" },
  { mk: "Волк", en: "Wolf", phonetic: "", category: "words" },
  { mk: "Овца", en: "Sheep", phonetic: "", category: "words" },
  { mk: "Работа", en: "Work", phonetic: "", category: "words" },
  { mk: "Школа", en: "School", phonetic: "", category: "words" },
  { mk: "Универзитет", en: "University", phonetic: "", category: "words" },
  { mk: "Пари", en: "Money", phonetic: "", category: "words" },
  { mk: "Време", en: "Time / weather", phonetic: "", category: "words" },
  { mk: "Живот", en: "Life", phonetic: "", category: "words" },
  { mk: "Љубов", en: "Love", phonetic: "", category: "words" },
  { mk: "Среќа", en: "Happiness / luck", phonetic: "", category: "words" },
  { mk: "Страшно", en: "Scary", phonetic: "", category: "words" },
  { mk: "Смешно", en: "Funny", phonetic: "", category: "words" },
  { mk: "Важно", en: "Important", phonetic: "", category: "words" },
  { mk: "Лесно", en: "Easy", phonetic: "", category: "words" },
  { mk: "Тешко", en: "Hard / difficult", phonetic: "", category: "words" },
  { mk: "Отворено", en: "Open", phonetic: "", category: "words" },
  { mk: "Затворено", en: "Closed", phonetic: "", category: "words" },
  { mk: "Чисто", en: "Clean", phonetic: "", category: "words" },
  { mk: "Валкано", en: "Dirty", phonetic: "", category: "words" },
  { mk: "Спиење", en: "Sleep", phonetic: "", category: "words" },
  { mk: "Сон", en: "Dream", phonetic: "", category: "words" },
  { mk: "Работам", en: "I work", phonetic: "", category: "words" },
  { mk: "Јадам", en: "I eat", phonetic: "", category: "words" },
  { mk: "Пијам", en: "I drink", phonetic: "", category: "words" },
  { mk: "Одам", en: "I go", phonetic: "", category: "words" },
  { mk: "Доаѓам", en: "I come", phonetic: "", category: "words" },
  { mk: "Гледам", en: "I see / watch", phonetic: "", category: "words" },
  { mk: "Слушам", en: "I listen", phonetic: "", category: "words" },
  { mk: "Зборувам", en: "I speak", phonetic: "", category: "words" },
  { mk: "Читам", en: "I read", phonetic: "", category: "words" },
  { mk: "Пишувам", en: "I write", phonetic: "", category: "words" },
  { mk: "Учам", en: "I learn / study", phonetic: "", category: "words" },
  { mk: "Знам", en: "I know", phonetic: "", category: "words" },
  { mk: "Сакам", en: "I love / want", phonetic: "", category: "words" },
  { mk: "Мразам", en: "I hate", phonetic: "", category: "words" },
  { mk: "Кино", en: "Cinema", phonetic: "", category: "words" },
  { mk: "Театар", en: "Theater", phonetic: "", category: "words" },
  { mk: "Музика", en: "Music", phonetic: "", category: "words" },
  { mk: "Песна", en: "Song", phonetic: "", category: "words" },
  { mk: "Филм", en: "Movie", phonetic: "", category: "words" },
  { mk: "Игра", en: "Game", phonetic: "", category: "words" },
  { mk: "Спорт", en: "Sport", phonetic: "", category: "words" },
  { mk: "Фудбал", en: "Football / soccer", phonetic: "", category: "words" },
  { mk: "Кошарка", en: "Basketball", phonetic: "", category: "words" },
  { mk: "Плажа", en: "Beach", phonetic: "", category: "words" },
  { mk: "Парк", en: "Park", phonetic: "", category: "words" },
  { mk: "Магасин", en: "Shop / store", phonetic: "", category: "words" },
  { mk: "Пазар", en: "Market", phonetic: "", category: "words" },
  { mk: "Болница", en: "Hospital", phonetic: "", category: "words" },
  { mk: "Артека", en: "Pharmacy", phonetic: "", category: "words" },
  { mk: "Банка", en: "Bank", phonetic: "", category: "words" },
  { mk: "Ресторан", en: "Restaurant", phonetic: "", category: "words" },
  { mk: "Станица", en: "Station", phonetic: "", category: "words" },
  { mk: "Пасош", en: "Passport", phonetic: "", category: "words" },
  { mk: "Прашање", en: "Question", phonetic: "", category: "words" },
  { mk: "Одговор", en: "Answer", phonetic: "", category: "words" },
  { mk: "Вистина", en: "Truth", phonetic: "", category: "words" },
  { mk: "Лага", en: "Lie", phonetic: "", category: "words" },
  { mk: "Надеж", en: "Hope", phonetic: "", category: "words" },
  { mk: "Страв", en: "Fear", phonetic: "", category: "words" },
  { mk: "Радост", en: "Joy", phonetic: "", category: "words" },
  { mk: "Тага", en: "Sadness", phonetic: "", category: "words" },
  { mk: "Гнев", en: "Anger", phonetic: "", category: "words" },
  { mk: "Мир", en: "Peace", phonetic: "", category: "words" },
  { mk: "Војна", en: "War", phonetic: "", category: "words" },
  { mk: "Слобода", en: "Freedom", phonetic: "", category: "words" },
  { mk: "Правда", en: "Justice", phonetic: "", category: "words" },
  { mk: "Закон", en: "Law", phonetic: "", category: "words" },
  { mk: "Правило", en: "Rule", phonetic: "", category: "words" },
  { mk: "План", en: "Plan", phonetic: "", category: "words" },
  { mk: "Идеја", en: "Idea", phonetic: "", category: "words" },
  { mk: "Проблем", en: "Problem", phonetic: "", category: "words" },
  { mk: "Решение", en: "Solution", phonetic: "", category: "words" },
  { mk: "Успех", en: "Success", phonetic: "", category: "words" },
  { mk: "Неуспех", en: "Failure", phonetic: "", category: "words" },
  { mk: "Образование", en: "Education", phonetic: "", category: "words" },
  { mk: "Култура", en: "Culture", phonetic: "", category: "words" },
  { mk: "Историја", en: "History", phonetic: "", category: "words" },
  { mk: "Географија", en: "Geography", phonetic: "", category: "words" },
  { mk: "Наука", en: "Science", phonetic: "", category: "words" },
  { mk: "Математика", en: "Mathematics", phonetic: "", category: "words" },
  { mk: "Јазик", en: "Language", phonetic: "", category: "words" },
  { mk: "Речник", en: "Dictionary", phonetic: "", category: "words" },
  { mk: "Писмо", en: "Letter / writing", phonetic: "", category: "words" },
  { mk: "Број", en: "Number", phonetic: "", category: "words" },
  { mk: "Име", en: "Name", phonetic: "", category: "words" },
  { mk: "Презиме", en: "Surname", phonetic: "", category: "words" },
  { mk: "Адреса", en: "Address", phonetic: "", category: "words" },
  { mk: "Градина", en: "Garden", phonetic: "", category: "words" },
  { mk: "Брег", en: "Coast / shore", phonetic: "", category: "words" },
  { mk: "Песок", en: "Sand", phonetic: "", category: "words" },
  { mk: "Камен", en: "Stone / rock", phonetic: "", category: "words" },
  { mk: "Злато", en: "Gold", phonetic: "", category: "words" },
  { mk: "Сребро", en: "Silver", phonetic: "", category: "words" },
  { mk: "Железо", en: "Iron", phonetic: "", category: "words" },
  { mk: "Стакло", en: "Glass", phonetic: "", category: "words" },
  { mk: "Пластика", en: "Plastic", phonetic: "", category: "words" },
  { mk: "Масхина", en: "Machine", phonetic: "", category: "words" },
  { mk: "Енергија", en: "Energy", phonetic: "", category: "words" },
  { mk: "Порака", en: "Message", phonetic: "", category: "words" },
  { mk: "Слика", en: "Picture / photo", phonetic: "", category: "words" },
  { mk: "Боја", en: "Color / paint", phonetic: "", category: "words" },
  { mk: "Форма", en: "Shape / form", phonetic: "", category: "words" },
  { mk: "Глас", en: "Voice / vote", phonetic: "", category: "words" },
  { mk: "Мирис", en: "Smell", phonetic: "", category: "words" },
  { mk: "Вкус", en: "Taste", phonetic: "", category: "words" },
  { mk: "Допир", en: "Touch", phonetic: "", category: "words" },
  { mk: "Чувство", en: "Feeling", phonetic: "", category: "words" },
  { mk: "Мисла", en: "Thought", phonetic: "", category: "words" },
  { mk: "Спомен", en: "Memory", phonetic: "", category: "words" },
  { mk: "Искуство", en: "Experience", phonetic: "", category: "words" },
  { mk: "Патување", en: "Travel / trip", phonetic: "", category: "words" },
  { mk: "Одмор", en: "Vacation / rest", phonetic: "", category: "words" },
  { mk: "Празник", en: "Holiday", phonetic: "", category: "words" },
  { mk: "Недела", en: "Week", phonetic: "", category: "words" },
  { mk: "Месес", en: "Month", phonetic: "", category: "words" },
  { mk: "Година", en: "Year", phonetic: "", category: "words" },
  { mk: "Век", en: "Century", phonetic: "", category: "words" },
  { mk: "Час", en: "Hour", phonetic: "", category: "words" },
  { mk: "Минута", en: "Minute", phonetic: "", category: "words" },
  { mk: "Секунда", en: "Second", phonetic: "", category: "words" },
  { mk: "Утро", en: "Morning", phonetic: "", category: "words" },
  { mk: "Пладне", en: "Noon", phonetic: "", category: "words" },
  { mk: "Вечер", en: "Evening", phonetic: "", category: "words" },
  { mk: "Нокј", en: "Night", phonetic: "", category: "words" },
  { mk: "Полноќ", en: "Midnight", phonetic: "", category: "words" },
  { mk: "Полека", en: "Slowly", phonetic: "", category: "words" },
  { mk: "Многу", en: "Very / a lot", phonetic: "", category: "words" },
  { mk: "Малку", en: "A little", phonetic: "", category: "words" },
  { mk: "Доста", en: "Enough / quite", phonetic: "", category: "words" },
  { mk: "Премногу", en: "Too much", phonetic: "", category: "words" },
  { mk: "Сите", en: "All", phonetic: "", category: "words" },
  { mk: "Ништо", en: "Nothing", phonetic: "", category: "words" },
  { mk: "Нешто", en: "Something", phonetic: "", category: "words" },
  { mk: "Секој", en: "Every / each", phonetic: "", category: "words" },
  { mk: "Други", en: "Other / others", phonetic: "", category: "words" },
  { mk: "Последен", en: "Last", phonetic: "", category: "words" },
  { mk: "Прв", en: "First", phonetic: "", category: "words" },
  { mk: "Втор", en: "Second", phonetic: "", category: "words" },
  { mk: "Трет", en: "Third", phonetic: "", category: "words" },
  { mk: "Еднакво", en: "Equal / the same", phonetic: "", category: "words" },
  { mk: "Различно", en: "Different", phonetic: "", category: "words" },
  { mk: "Едноставно", en: "Simple", phonetic: "", category: "words" },
  { mk: "Слозхено", en: "Complex", phonetic: "", category: "words" },
  { mk: "Сигурно", en: "Sure / safe", phonetic: "", category: "words" },
  { mk: "Орасно", en: "Dangerous", phonetic: "", category: "words" },
  { mk: "Болен", en: "Sick", phonetic: "", category: "words" },
  { mk: "Лек", en: "Medicine", phonetic: "", category: "words" },
  { mk: "Болка", en: "Pain", phonetic: "", category: "words" },
  { mk: "Темрература", en: "Temperature", phonetic: "", category: "words" },
  { mk: "Мускул", en: "Muscle", phonetic: "", category: "words" },
  { mk: "Мозок", en: "Brain", phonetic: "", category: "words" },
  { mk: "Дусха", en: "Soul", phonetic: "", category: "words" },
  { mk: "Тело", en: "Body", phonetic: "", category: "words" },
  { mk: "Бебе", en: "Baby", phonetic: "", category: "words" },
  { mk: "Возраст", en: "Age", phonetic: "", category: "words" },
  { mk: "Роденден", en: "Birthday", phonetic: "", category: "words" },
  { mk: "Брак", en: "Marriage", phonetic: "", category: "words" },
  { mk: "Свадба", en: "Wedding", phonetic: "", category: "words" },
  { mk: "Смрт", en: "Death", phonetic: "", category: "words" },
  { mk: "Гроб", en: "Grave", phonetic: "", category: "words" },
  { mk: "Црква", en: "Church", phonetic: "", category: "words" },
  { mk: "топла", en: "warm", phonetic: "", category: "words" },
  { mk: "збор", en: "word", phonetic: "", category: "words" },
  { mk: "воздух", en: "air", phonetic: "", category: "words" },
  { mk: "мали", en: "small", phonetic: "", category: "words" },
  { mk: "крајот", en: "end", phonetic: "", category: "words" },
  { mk: "дома", en: "home", phonetic: "", category: "words" },
  { mk: "страна", en: "side / page", phonetic: "", category: "words" },
  { mk: "порт", en: "port", phonetic: "", category: "words" },
  { mk: "магија", en: "magic", phonetic: "", category: "words" },
  { mk: "земјиште", en: "land", phonetic: "", category: "words" },
  { mk: "мора", en: "must / obligation", phonetic: "", category: "words" },
  { mk: "голема", en: "big", phonetic: "", category: "words" },
  { mk: "висок", en: "high", phonetic: "", category: "words" },
  { mk: "чин", en: "act / deed", phonetic: "", category: "words" },
  { mk: "мажи", en: "men", phonetic: "", category: "words" },
  { mk: "промена", en: "change", phonetic: "", category: "words" },
  { mk: "светлината", en: "light", phonetic: "", category: "words" },
  { mk: "вид", en: "kind / type", phonetic: "", category: "words" },
  { mk: "треба", en: "need", phonetic: "", category: "words" },
  { mk: "се обиде", en: "try", phonetic: "", category: "words" },
  { mk: "животните", en: "animal", phonetic: "", category: "words" },
  { mk: "точка", en: "point", phonetic: "", category: "words" },
  { mk: "светот", en: "world", phonetic: "", category: "words" },
  { mk: "во близина", en: "near", phonetic: "", category: "words" },
  { mk: "изградба", en: "build", phonetic: "", category: "words" },
  { mk: "само", en: "self", phonetic: "", category: "words" },
  { mk: "земјата", en: "earth", phonetic: "", category: "words" },
  { mk: "нови", en: "new", phonetic: "", category: "words" },
  { mk: "дел", en: "part", phonetic: "", category: "words" },
  { mk: "место", en: "place", phonetic: "", category: "words" },
  { mk: "назад", en: "back", phonetic: "", category: "words" },
  { mk: "круг", en: "round", phonetic: "", category: "words" },
  { mk: "шоу", en: "show", phonetic: "", category: "words" },
  { mk: "казна", en: "punishment / sentence", phonetic: "", category: "words" },
  { mk: "ниска", en: "low", phonetic: "", category: "words" },
  { mk: "линија", en: "line", phonetic: "", category: "words" },
  { mk: "разликуваат", en: "differ", phonetic: "", category: "words" },
  { mk: "возврат", en: "return / turn", phonetic: "", category: "words" },
  { mk: "причина", en: "cause", phonetic: "", category: "words" },
  { mk: "значи", en: "mean", phonetic: "", category: "words" },
  { mk: "потег", en: "move", phonetic: "", category: "words" },
  { mk: "право", en: "right / law", phonetic: "", category: "words" },
  { mk: "момчето", en: "boy", phonetic: "", category: "words" },
  { mk: "стари", en: "old", phonetic: "", category: "words" },
  { mk: "исто", en: "same", phonetic: "", category: "words" },
  { mk: "начин", en: "way", phonetic: "", category: "words" },
  { mk: "долг", en: "long", phonetic: "", category: "words" },
  { mk: "ден", en: "day", phonetic: "", category: "words" },
  { mk: "прва", en: "first", phonetic: "", category: "words" },
  { mk: "стојат", en: "stand", phonetic: "", category: "words" },
  { mk: "сопствени", en: "own", phonetic: "", category: "words" },
  { mk: "страница", en: "page", phonetic: "", category: "words" },
  { mk: "земја", en: "country", phonetic: "", category: "words" },
  { mk: "најде", en: "found", phonetic: "", category: "words" },
  { mk: "училиште", en: "school", phonetic: "", category: "words" },
  { mk: "расте", en: "grow", phonetic: "", category: "words" },
  { mk: "студија", en: "study", phonetic: "", category: "words" },
  { mk: "растенија", en: "plant", phonetic: "", category: "words" },
  { mk: "покритие", en: "cover", phonetic: "", category: "words" },
  { mk: "храна", en: "food", phonetic: "", category: "words" },
  { mk: "сонцето", en: "sun", phonetic: "", category: "words" },
  { mk: "состојба", en: "state", phonetic: "", category: "words" },
  { mk: "последните", en: "last", phonetic: "", category: "words" },
  { mk: "нека", en: "let", phonetic: "", category: "words" },
  { mk: "мисли", en: "thought", phonetic: "", category: "words" },
  { mk: "фарма", en: "farm", phonetic: "", category: "words" },
  { mk: "почеток", en: "start", phonetic: "", category: "words" },
  { mk: "приказна", en: "story", phonetic: "", category: "words" },
  { mk: "видов", en: "saw", phonetic: "", category: "words" },
  { mk: "бегство", en: "run", phonetic: "", category: "words" },
  { mk: "прес-", en: "press", phonetic: "", category: "words" },
  { mk: "ноќ", en: "night", phonetic: "", category: "words" },
  { mk: "вистински", en: "real", phonetic: "", category: "words" },
  { mk: "неколку", en: "few", phonetic: "", category: "words" },
  { mk: "Северна", en: "north", phonetic: "", category: "words" },
  { mk: "носат", en: "carry", phonetic: "", category: "words" },
  { mk: "науката", en: "science", phonetic: "", category: "words" },
  { mk: "јадете", en: "eat", phonetic: "", category: "words" },
  { mk: "започна", en: "began", phonetic: "", category: "words" },
  { mk: "планински", en: "mountain (adj.)", phonetic: "", category: "words" },
  { mk: "база", en: "base", phonetic: "", category: "words" },
  { mk: "намалување на", en: "reduction / cut", phonetic: "", category: "words" },
  { mk: "сигурни", en: "sure", phonetic: "", category: "words" },
  { mk: "лице", en: "face", phonetic: "", category: "words" },
  { mk: "главната", en: "main", phonetic: "", category: "words" },
  { mk: "отворен", en: "open", phonetic: "", category: "words" },
  { mk: "изгледа", en: "seem", phonetic: "", category: "words" },
  { mk: "заедно", en: "together", phonetic: "", category: "words" },
  { mk: "следна", en: "next", phonetic: "", category: "words" },
  { mk: "деца", en: "children", phonetic: "", category: "words" },
  { mk: "започне", en: "begin", phonetic: "", category: "words" },
  { mk: "доби", en: "got", phonetic: "", category: "words" },
  { mk: "прошетка", en: "walk", phonetic: "", category: "words" },
  { mk: "пример", en: "example", phonetic: "", category: "words" },
  { mk: "олеснување", en: "relief / ease", phonetic: "", category: "words" },
  { mk: "група", en: "group", phonetic: "", category: "words" },
  { mk: "знак", en: "mark", phonetic: "", category: "words" },
  { mk: "милја", en: "mile", phonetic: "", category: "words" },
  { mk: "нозе", en: "feet", phonetic: "", category: "words" },
  { mk: "грижа", en: "care", phonetic: "", category: "words" },
  { mk: "вториот", en: "second", phonetic: "", category: "words" },
  { mk: "доволно", en: "enough", phonetic: "", category: "words" },
  { mk: "обичен", en: "plain", phonetic: "", category: "words" },
  { mk: "вообичаената", en: "usual", phonetic: "", category: "words" },
  { mk: "млади", en: "young", phonetic: "", category: "words" },
  { mk: "подготвени", en: "ready", phonetic: "", category: "words" },
  { mk: "некогаш", en: "ever", phonetic: "", category: "words" },
  { mk: "црвена", en: "red", phonetic: "", category: "words" },
  { mk: "листа", en: "list", phonetic: "", category: "words" },
  { mk: "иако", en: "though", phonetic: "", category: "words" },
  { mk: "се чувствуваат", en: "feel", phonetic: "", category: "words" },
  { mk: "разговор", en: "talk", phonetic: "", category: "words" },
  { mk: "птици", en: "bird", phonetic: "", category: "words" },
  { mk: "наскоро", en: "soon", phonetic: "", category: "words" },
  { mk: "директна", en: "direct", phonetic: "", category: "words" },
  { mk: "претставува", en: "pose", phonetic: "", category: "words" },
  { mk: "напушти", en: "leave", phonetic: "", category: "words" },
  { mk: "мерење на", en: "measurement", phonetic: "", category: "words" },
  { mk: "производ", en: "product", phonetic: "", category: "words" },
  { mk: "црна", en: "black", phonetic: "", category: "words" },
  { mk: "краток", en: "short", phonetic: "", category: "words" },
  { mk: "броеви", en: "numeral", phonetic: "", category: "words" },
  { mk: "класа", en: "class", phonetic: "", category: "words" },
  { mk: "се случи", en: "happen", phonetic: "", category: "words" },
  { mk: "целосна", en: "complete", phonetic: "", category: "words" },
  { mk: "брод", en: "ship", phonetic: "", category: "words" },
  { mk: "област", en: "area", phonetic: "", category: "words" },
  { mk: "половина", en: "half", phonetic: "", category: "words" },
  { mk: "рок", en: "rock", phonetic: "", category: "words" },
  { mk: "цел", en: "order", phonetic: "", category: "words" },
  { mk: "југ", en: "south", phonetic: "", category: "words" },
  { mk: "проблемот", en: "problem", phonetic: "", category: "words" },
  { mk: "парче", en: "piece", phonetic: "", category: "words" },
  { mk: "изјави", en: "told", phonetic: "", category: "words" },
  { mk: "знаеја", en: "knew", phonetic: "", category: "words" },
  { mk: "помине", en: "pass", phonetic: "", category: "words" },
  { mk: "врвот", en: "top", phonetic: "", category: "words" },
  { mk: "целата", en: "whole", phonetic: "", category: "words" },
  { mk: "крал", en: "king", phonetic: "", category: "words" },
  { mk: "инчен", en: "inch", phonetic: "", category: "words" },
  { mk: "мултиплицираат", en: "multiply", phonetic: "", category: "words" },
  { mk: "Се разбира", en: "course", phonetic: "", category: "words" },
  { mk: "остане", en: "stay", phonetic: "", category: "words" },
  { mk: "на тркала", en: "wheel", phonetic: "", category: "words" },
  { mk: "сила", en: "force", phonetic: "", category: "words" },
  { mk: "сина", en: "blue", phonetic: "", category: "words" },
  { mk: "објект", en: "object", phonetic: "", category: "words" },
  { mk: "одлучи", en: "decide", phonetic: "", category: "words" },
  { mk: "површината", en: "surface", phonetic: "", category: "words" },
  { mk: "длабоко", en: "deep", phonetic: "", category: "words" },
  { mk: "месечината", en: "moon", phonetic: "", category: "words" },
  { mk: "систем", en: "system", phonetic: "", category: "words" },
  { mk: "зафатен", en: "busy", phonetic: "", category: "words" },
  { mk: "тест", en: "test", phonetic: "", category: "words" },
  { mk: "рекорд", en: "record", phonetic: "", category: "words" },
  { mk: "заеднички", en: "common", phonetic: "", category: "words" },
  { mk: "можно", en: "possible", phonetic: "", category: "words" },
  { mk: "наместо", en: "stead", phonetic: "", category: "words" },
  { mk: "сува", en: "dry", phonetic: "", category: "words" },
  { mk: "се прашувам", en: "wonder", phonetic: "", category: "words" },
  { mk: "смеа", en: "laugh", phonetic: "", category: "words" },
  { mk: "илјади", en: "thousand", phonetic: "", category: "words" },
  { mk: "пред", en: "ago", phonetic: "", category: "words" },
  { mk: "трчаше", en: "ran", phonetic: "", category: "words" },
  { mk: "изедначуваат", en: "equate", phonetic: "", category: "words" },
  { mk: "Мис", en: "fly (insect)", phonetic: "", category: "words" },
  { mk: "донесе", en: "brought", phonetic: "", category: "words" },
  { mk: "топлина", en: "heat", phonetic: "", category: "words" },
  { mk: "гуми", en: "tire", phonetic: "", category: "words" },
  { mk: "далечни", en: "distant", phonetic: "", category: "words" },
  { mk: "пополнување", en: "fill", phonetic: "", category: "words" },
  { mk: "исток", en: "east", phonetic: "", category: "words" },
  { mk: "единица", en: "unit", phonetic: "", category: "words" },
  { mk: "моќ", en: "power", phonetic: "", category: "words" },
  { mk: "градот", en: "town", phonetic: "", category: "words" },
  { mk: "парична казна", en: "fine (penalty)", phonetic: "", category: "words" },
  { mk: "одредени", en: "certain", phonetic: "", category: "words" },
  { mk: "лета", en: "fly", phonetic: "", category: "words" },
  { mk: "паѓаат", en: "fall", phonetic: "", category: "words" },
  { mk: "доведе", en: "lead", phonetic: "", category: "words" },
  { mk: "крик", en: "cry", phonetic: "", category: "words" },
  { mk: "темно", en: "dark", phonetic: "", category: "words" },
  { mk: "машина", en: "machine", phonetic: "", category: "words" },
  { mk: "белешка", en: "note", phonetic: "", category: "words" },
  { mk: "чекаат", en: "wait", phonetic: "", category: "words" },
  { mk: "кутија", en: "box", phonetic: "", category: "words" },
  { mk: "именка", en: "noun", phonetic: "", category: "words" },
  { mk: "поле", en: "field", phonetic: "", category: "words" },
  { mk: "точни", en: "correct", phonetic: "", category: "words" },
  { mk: "фунти", en: "pound", phonetic: "", category: "words" },
  { mk: "убавина", en: "beauty", phonetic: "", category: "words" },
  { mk: "диск", en: "drive", phonetic: "", category: "words" },
  { mk: "стоеше", en: "stood", phonetic: "", category: "words" },
  { mk: "содржи", en: "contain", phonetic: "", category: "words" },
  { mk: "учат", en: "teach", phonetic: "", category: "words" },
  { mk: "конечна", en: "final", phonetic: "", category: "words" },
  { mk: "зелена", en: "green", phonetic: "", category: "words" },
  { mk: "ох", en: "oh", phonetic: "", category: "words" },
  { mk: "развие", en: "develop", phonetic: "", category: "words" },
  { mk: "океанот", en: "ocean", phonetic: "", category: "words" },
  { mk: "слободен", en: "free", phonetic: "", category: "words" },
  { mk: "силна", en: "strong", phonetic: "", category: "words" },
  { mk: "специјални", en: "special", phonetic: "", category: "words" },
  { mk: "ум", en: "mind", phonetic: "", category: "words" },
  { mk: "зад", en: "behind", phonetic: "", category: "words" },
  { mk: "јасно", en: "clear", phonetic: "", category: "words" },
  { mk: "опашка", en: "tail", phonetic: "", category: "words" },
  { mk: "производство на", en: "production", phonetic: "", category: "words" },
  { mk: "Всушност", en: "in fact", phonetic: "", category: "words" },
  { mk: "простор", en: "space", phonetic: "", category: "words" },
  { mk: "најдобрите", en: "best", phonetic: "", category: "words" },
  { mk: "подобро", en: "better", phonetic: "", category: "words" },
  { mk: "чекор", en: "step", phonetic: "", category: "words" },
  { mk: "почетокот", en: "early", phonetic: "", category: "words" },
  { mk: "запад", en: "west", phonetic: "", category: "words" },
  { mk: "интерес", en: "interest", phonetic: "", category: "words" },
  { mk: "достигне", en: "reach", phonetic: "", category: "words" },
  { mk: "глагол", en: "verb", phonetic: "", category: "words" },
  { mk: "помалку", en: "less", phonetic: "", category: "words" },
  { mk: "наутро", en: "morning", phonetic: "", category: "words" },
  { mk: "едноставен", en: "simple", phonetic: "", category: "words" },
  { mk: "повеќе", en: "several", phonetic: "", category: "words" },
  { mk: "самогласка", en: "vowel", phonetic: "", category: "words" },
  { mk: "постават", en: "lay", phonetic: "", category: "words" },
  { mk: "модел", en: "pattern", phonetic: "", category: "words" },
  { mk: "бавен", en: "slow", phonetic: "", category: "words" },
  { mk: "центар", en: "center", phonetic: "", category: "words" },
  { mk: "патот", en: "road", phonetic: "", category: "words" },
  { mk: "мапа", en: "map", phonetic: "", category: "words" },
  { mk: "ладна", en: "cold", phonetic: "", category: "words" },
  { mk: "најава", en: "notice", phonetic: "", category: "words" },
  { mk: "лов", en: "hunt", phonetic: "", category: "words" },
  { mk: "веројатно", en: "probable", phonetic: "", category: "words" },
  { mk: "возење", en: "ride", phonetic: "", category: "words" },
  { mk: "мобилен", en: "cell", phonetic: "", category: "words" },
  { mk: "веруваат", en: "believe", phonetic: "", category: "words" },
  { mk: "одеднаш", en: "sudden", phonetic: "", category: "words" },
  { mk: "плоштад", en: "square", phonetic: "", category: "words" },
  { mk: "должина", en: "length", phonetic: "", category: "words" },
  { mk: "уметност", en: "art", phonetic: "", category: "words" },
  { mk: "предмет", en: "subject", phonetic: "", category: "words" },
  { mk: "регионот", en: "region", phonetic: "", category: "words" },
  { mk: "големина", en: "size", phonetic: "", category: "words" },
  { mk: "тежина", en: "weight", phonetic: "", category: "words" },
  { mk: "општо", en: "general", phonetic: "", category: "words" },
  { mk: "мраз", en: "ice", phonetic: "", category: "words" },
  { mk: "пар", en: "pair", phonetic: "", category: "words" },
  { mk: "јаз", en: "divide", phonetic: "", category: "words" },
  { mk: "слог", en: "syllable", phonetic: "", category: "words" },
  { mk: "гренд", en: "grand", phonetic: "", category: "words" },
  { mk: "топка", en: "ball", phonetic: "", category: "words" },
  { mk: "бран", en: "wave", phonetic: "", category: "words" },
  { mk: "капка", en: "drop", phonetic: "", category: "words" },
  { mk: "срцето", en: "heart", phonetic: "", category: "words" },
  { mk: "моментов", en: "present", phonetic: "", category: "words" },
  { mk: "тешки", en: "heavy", phonetic: "", category: "words" },
  { mk: "танц", en: "dance", phonetic: "", category: "words" },
  { mk: "моторот", en: "engine", phonetic: "", category: "words" },
  { mk: "позиција", en: "position", phonetic: "", category: "words" },
  { mk: "широк", en: "wide", phonetic: "", category: "words" },
  { mk: "едро", en: "sail", phonetic: "", category: "words" },
  { mk: "материјал", en: "material", phonetic: "", category: "words" },
  { mk: "трка", en: "race", phonetic: "", category: "words" },
  { mk: "продавница", en: "store", phonetic: "", category: "words" },
  { mk: "осамен", en: "lone", phonetic: "", category: "words" },
  { mk: "вежби", en: "exercise", phonetic: "", category: "words" },
  { mk: "ѕид", en: "wall", phonetic: "", category: "words" },
  { mk: "фати", en: "catch", phonetic: "", category: "words" },
  { mk: "монтирање", en: "mount", phonetic: "", category: "words" },
  { mk: "сакаат", en: "wish", phonetic: "", category: "words" },
  { mk: "небото", en: "sky", phonetic: "", category: "words" },
  { mk: "одбор", en: "board", phonetic: "", category: "words" },
  { mk: "са", en: "sat", phonetic: "", category: "words" },
  { mk: "писмено", en: "written", phonetic: "", category: "words" },
  { mk: "диви", en: "wild", phonetic: "", category: "words" },
  { mk: "инструмент", en: "instrument", phonetic: "", category: "words" },
  { mk: "работ", en: "edge", phonetic: "", category: "words" },
  { mk: "посета", en: "visit", phonetic: "", category: "words" },
  { mk: "минатото", en: "past", phonetic: "", category: "words" },
  { mk: "мека", en: "soft", phonetic: "", category: "words" },
  { mk: "забава", en: "fun", phonetic: "", category: "words" },
  { mk: "светла", en: "bright", phonetic: "", category: "words" },
  { mk: "гас", en: "gas", phonetic: "", category: "words" },
  { mk: "месец", en: "month", phonetic: "", category: "words" },
  { mk: "милиони", en: "million", phonetic: "", category: "words" },
  { mk: "финиш", en: "finish", phonetic: "", category: "words" },
  { mk: "среќен", en: "happy", phonetic: "", category: "words" },
  { mk: "облечеш", en: "clothe", phonetic: "", category: "words" },
  { mk: "чудно", en: "strange", phonetic: "", category: "words" },
  { mk: "Поминаа", en: "gone", phonetic: "", category: "words" },
  { mk: "трговија", en: "trade", phonetic: "", category: "words" },
  { mk: "мелодијата", en: "melody", phonetic: "", category: "words" },
  { mk: "канцеларија", en: "office", phonetic: "", category: "words" },
  { mk: "ред", en: "row", phonetic: "", category: "words" },
  { mk: "устата", en: "mouth", phonetic: "", category: "words" },
  { mk: "точниот", en: "exact", phonetic: "", category: "words" },
  { mk: "симбол", en: "symbol", phonetic: "", category: "words" },
  { mk: "умре", en: "die", phonetic: "", category: "words" },
  { mk: "најмалку", en: "least", phonetic: "", category: "words" },
  { mk: "проблеми", en: "trouble", phonetic: "", category: "words" },
  { mk: "извик", en: "shout", phonetic: "", category: "words" },
  { mk: "освен", en: "except", phonetic: "", category: "words" },
  { mk: "напиша", en: "wrote", phonetic: "", category: "words" },
  { mk: "семе", en: "seed", phonetic: "", category: "words" },
  { mk: "тон", en: "tone", phonetic: "", category: "words" },
  { mk: "се приклучат", en: "join", phonetic: "", category: "words" },
  { mk: "чиста", en: "clean", phonetic: "", category: "words" },
  { mk: "пауза", en: "break", phonetic: "", category: "words" },
  { mk: "дама", en: "lady", phonetic: "", category: "words" },
  { mk: "двор", en: "yard", phonetic: "", category: "words" },
  { mk: "зголеми", en: "rise", phonetic: "", category: "words" },
  { mk: "лоша", en: "bad", phonetic: "", category: "words" },
  { mk: "удар", en: "blow", phonetic: "", category: "words" },
  { mk: "проценти", en: "cent", phonetic: "", category: "words" },
  { mk: "тимот", en: "team", phonetic: "", category: "words" },
  { mk: "жица", en: "wire", phonetic: "", category: "words" },
  { mk: "цена", en: "cost", phonetic: "", category: "words" },
  { mk: "изгубени", en: "lost", phonetic: "", category: "words" },
  { mk: "кафеава", en: "brown", phonetic: "", category: "words" },
  { mk: "еднакви", en: "equal", phonetic: "", category: "words" },
  { mk: "падна", en: "fell", phonetic: "", category: "words" },
  { mk: "проток", en: "flow", phonetic: "", category: "words" },
  { mk: "фер", en: "fair", phonetic: "", category: "words" },
  { mk: "контрола", en: "control", phonetic: "", category: "words" },
  { mk: "децимална", en: "decimal", phonetic: "", category: "words" },
  { mk: "друг", en: "else", phonetic: "", category: "words" },
  { mk: "случај", en: "case", phonetic: "", category: "words" },
  { mk: "средината", en: "middle", phonetic: "", category: "words" },
  { mk: "убие", en: "kill", phonetic: "", category: "words" },
  { mk: "езерото", en: "lake", phonetic: "", category: "words" },
  { mk: "момент", en: "moment", phonetic: "", category: "words" },
  { mk: "скала", en: "scale", phonetic: "", category: "words" },
  { mk: "гласно", en: "loud", phonetic: "", category: "words" },
  { mk: "директно", en: "straight", phonetic: "", category: "words" },
  { mk: "согласка", en: "consonant", phonetic: "", category: "words" },
  { mk: "нација", en: "nation", phonetic: "", category: "words" },
  { mk: "брзина", en: "speed", phonetic: "", category: "words" },
  { mk: "метод", en: "method", phonetic: "", category: "words" },
  { mk: "орган", en: "organ", phonetic: "", category: "words" },
  { mk: "плати", en: "pay", phonetic: "", category: "words" },
  { mk: "секција", en: "section", phonetic: "", category: "words" },
  { mk: "фустан", en: "dress", phonetic: "", category: "words" },
  { mk: "изненадување", en: "surprise", phonetic: "", category: "words" },
  { mk: "тивка", en: "quiet", phonetic: "", category: "words" },
  { mk: "искачувањето", en: "climb", phonetic: "", category: "words" },
  { mk: "кул", en: "cool", phonetic: "", category: "words" },
  { mk: "дизајн", en: "design", phonetic: "", category: "words" },
  { mk: "сиромашните", en: "poor", phonetic: "", category: "words" },
  { mk: "експеримент", en: "experiment", phonetic: "", category: "words" },
  { mk: "дното", en: "bottom", phonetic: "", category: "words" },
  { mk: "клучот", en: "key", phonetic: "", category: "words" },
  { mk: "стап", en: "stick", phonetic: "", category: "words" },
  { mk: "Стан", en: "apartment / flat", phonetic: "", category: "words" },
  { mk: "насмевка", en: "smile", phonetic: "", category: "words" },
  { mk: "браздата", en: "crease", phonetic: "", category: "words" },
  { mk: "дупка", en: "hole", phonetic: "", category: "words" },
  { mk: "скок", en: "jump", phonetic: "", category: "words" },
  { mk: "корен", en: "root", phonetic: "", category: "words" },
  { mk: "купување", en: "buy", phonetic: "", category: "words" },
  { mk: "метал", en: "metal", phonetic: "", category: "words" },
  { mk: "дали", en: "whether", phonetic: "", category: "words" },
  { mk: "став", en: "paragraph", phonetic: "", category: "words" },
  { mk: "третиот", en: "third", phonetic: "", category: "words" },
  { mk: "Одржана", en: "held", phonetic: "", category: "words" },
  { mk: "Кук", en: "hook", phonetic: "", category: "words" },
  { mk: "кат", en: "floor", phonetic: "", category: "words" },
  { mk: "резултат", en: "result", phonetic: "", category: "words" },
  { mk: "изгори", en: "burn", phonetic: "", category: "words" },
  { mk: "рид", en: "hill", phonetic: "", category: "words" },
  { mk: "безбедно", en: "safe", phonetic: "", category: "words" },
  { mk: "тип", en: "type", phonetic: "", category: "words" },
  { mk: "копија", en: "copy", phonetic: "", category: "words" },
  { mk: "фраза", en: "phrase", phonetic: "", category: "words" },
  { mk: "молчи", en: "silent", phonetic: "", category: "words" },
  { mk: "почвата", en: "soil", phonetic: "", category: "words" },
  { mk: "ролна", en: "roll", phonetic: "", category: "words" },
  { mk: "температура", en: "temperature", phonetic: "", category: "words" },
  { mk: "индустрија", en: "industry", phonetic: "", category: "words" },
  { mk: "вредност", en: "value", phonetic: "", category: "words" },
  { mk: "борба", en: "fight", phonetic: "", category: "words" },
  { mk: "победи", en: "beat", phonetic: "", category: "words" },
  { mk: "возбуди", en: "excite", phonetic: "", category: "words" },
  { mk: "природни", en: "natural", phonetic: "", category: "words" },
  { mk: "поглед", en: "view", phonetic: "", category: "words" },
  { mk: "смисла", en: "sense", phonetic: "", category: "words" },
  { mk: "капитал", en: "capital", phonetic: "", category: "words" },
  { mk: "опасност", en: "danger", phonetic: "", category: "words" },
  { mk: "богата", en: "rich", phonetic: "", category: "words" },
  { mk: "дебели", en: "thick", phonetic: "", category: "words" },
  { mk: "војник", en: "soldier", phonetic: "", category: "words" },
  { mk: "процес", en: "process", phonetic: "", category: "words" },
  { mk: "работи", en: "operate", phonetic: "", category: "words" },
  { mk: "пракса", en: "practice", phonetic: "", category: "words" },
  { mk: "посебна", en: "separate", phonetic: "", category: "words" },
  { mk: "лекар", en: "doctor", phonetic: "", category: "words" },
  { mk: "ве молиме", en: "please", phonetic: "", category: "words" },
  { mk: "заштита на", en: "protect", phonetic: "", category: "words" },
  { mk: "модерен", en: "modern", phonetic: "", category: "words" },
  { mk: "елемент", en: "element", phonetic: "", category: "words" },
  { mk: "хит", en: "hit", phonetic: "", category: "words" },
  { mk: "агол", en: "corner", phonetic: "", category: "words" },
  { mk: "партија", en: "party", phonetic: "", category: "words" },
  { mk: "снабдување", en: "supply", phonetic: "", category: "words" },
  { mk: "чија", en: "whose", phonetic: "", category: "words" },
  { mk: "лоцирајте", en: "locate", phonetic: "", category: "words" },
  { mk: "прстен", en: "ring", phonetic: "", category: "words" },
  { mk: "карактер", en: "character", phonetic: "", category: "words" },
  { mk: "инсекти", en: "insect", phonetic: "", category: "words" },
  { mk: "фатени", en: "caught", phonetic: "", category: "words" },
  { mk: "период", en: "period", phonetic: "", category: "words" },
  { mk: "радио", en: "radio", phonetic: "", category: "words" },
  { mk: "зборуваше", en: "spoke", phonetic: "", category: "words" },
  { mk: "атомот", en: "atom", phonetic: "", category: "words" },
  { mk: "човечки", en: "human", phonetic: "", category: "words" },
  { mk: "ефект", en: "effect", phonetic: "", category: "words" },
  { mk: "електрични", en: "electric", phonetic: "", category: "words" },
  { mk: "очекуваме", en: "expect", phonetic: "", category: "words" },
  { mk: "железнички", en: "rail", phonetic: "", category: "words" },
  { mk: "на тој начин", en: "thus", phonetic: "", category: "words" },
  { mk: "нежен", en: "gentle", phonetic: "", category: "words" },
  { mk: "капетан", en: "captain", phonetic: "", category: "words" },
  { mk: "Претпоставувам", en: "guess", phonetic: "", category: "words" },
  { mk: "потребно", en: "necessary", phonetic: "", category: "words" },
  { mk: "остри", en: "sharp", phonetic: "", category: "words" },
  { mk: "крило", en: "wing", phonetic: "", category: "words" },
  { mk: "миење", en: "wash", phonetic: "", category: "words" },
  { mk: "лилјак", en: "bat", phonetic: "", category: "words" },
  { mk: "толпата", en: "crowd", phonetic: "", category: "words" },
  { mk: "пченка", en: "corn", phonetic: "", category: "words" },
  { mk: "низа", en: "string", phonetic: "", category: "words" },
  { mk: "ѕвоно", en: "bell", phonetic: "", category: "words" },
  { mk: "Бришење", en: "wiping", phonetic: "", category: "words" },
  { mk: "цевка", en: "tube", phonetic: "", category: "words" },
  { mk: "познат", en: "famous", phonetic: "", category: "words" },
  { mk: "долар", en: "dollar", phonetic: "", category: "words" },
  { mk: "поток", en: "stream", phonetic: "", category: "words" },
  { mk: "тенка", en: "thin", phonetic: "", category: "words" },
  { mk: "триаголник", en: "triangle", phonetic: "", category: "words" },
  { mk: "планетата", en: "planet", phonetic: "", category: "words" },
  { mk: "брза", en: "hurry", phonetic: "", category: "words" },
  { mk: "главен", en: "chief", phonetic: "", category: "words" },
  { mk: "колонијата", en: "colony", phonetic: "", category: "words" },
  { mk: "часовник", en: "clock", phonetic: "", category: "words" },
  { mk: "рудникот", en: "mine", phonetic: "", category: "words" },
  { mk: "вратоврска", en: "tie", phonetic: "", category: "words" },
  { mk: "внесете", en: "enter", phonetic: "", category: "words" },
  { mk: "големи", en: "major", phonetic: "", category: "words" },
  { mk: "свежо", en: "fresh", phonetic: "", category: "words" },
  { mk: "Барај", en: "search", phonetic: "", category: "words" },
  { mk: "жолта", en: "yellow", phonetic: "", category: "words" },
  { mk: "пиштол", en: "gun", phonetic: "", category: "words" },
  { mk: "овозможи", en: "allow", phonetic: "", category: "words" },
  { mk: "печатење", en: "print", phonetic: "", category: "words" },
  { mk: "мртви", en: "dead", phonetic: "", category: "words" },
  { mk: "пустината", en: "desert", phonetic: "", category: "words" },
  { mk: "костум", en: "suit", phonetic: "", category: "words" },
  { mk: "тековната", en: "current", phonetic: "", category: "words" },
  { mk: "лифт", en: "lift", phonetic: "", category: "words" },
  { mk: "пристигнат", en: "arrive", phonetic: "", category: "words" },
  { mk: "господар", en: "master", phonetic: "", category: "words" },
  { mk: "родител", en: "parent", phonetic: "", category: "words" },
  { mk: "брегот", en: "shore", phonetic: "", category: "words" },
  { mk: "поделба", en: "division", phonetic: "", category: "words" },
  { mk: "лист", en: "sheet", phonetic: "", category: "words" },
  { mk: "супстанција", en: "substance", phonetic: "", category: "words" },
  { mk: "корист", en: "favor", phonetic: "", category: "words" },
  { mk: "поврзете", en: "connect", phonetic: "", category: "words" },
  { mk: "пост", en: "post", phonetic: "", category: "words" },
  { mk: "поминат", en: "spend", phonetic: "", category: "words" },
  { mk: "акорд", en: "chord", phonetic: "", category: "words" },
  { mk: "масти", en: "fat", phonetic: "", category: "words" },
  { mk: "мило", en: "glad", phonetic: "", category: "words" },
  { mk: "оригинални", en: "original", phonetic: "", category: "words" },
  { mk: "удел", en: "share", phonetic: "", category: "words" },
  { mk: "наплаќаат", en: "charge", phonetic: "", category: "words" },
  { mk: "соодветна", en: "proper", phonetic: "", category: "words" },
  { mk: "бар", en: "bar", phonetic: "", category: "words" },
  { mk: "понуда", en: "offer", phonetic: "", category: "words" },
  { mk: "сегмент", en: "segment", phonetic: "", category: "words" },
  { mk: "роб", en: "slave", phonetic: "", category: "words" },
  { mk: "патка", en: "duck", phonetic: "", category: "words" },
  { mk: "инстант", en: "instant", phonetic: "", category: "words" },
  { mk: "пазарот", en: "market", phonetic: "", category: "words" },
  { mk: "степен", en: "degree", phonetic: "", category: "words" },
  { mk: "доверат", en: "populate", phonetic: "", category: "words" },
  { mk: "драги", en: "dear", phonetic: "", category: "words" },
  { mk: "непријател", en: "enemy", phonetic: "", category: "words" },
  { mk: "одговори", en: "reply", phonetic: "", category: "words" },
  { mk: "поддршка", en: "support", phonetic: "", category: "words" },
  { mk: "говор", en: "speech", phonetic: "", category: "words" },
  { mk: "природата", en: "nature", phonetic: "", category: "words" },
  { mk: "опсег", en: "range", phonetic: "", category: "words" },
  { mk: "пареа", en: "steam", phonetic: "", category: "words" },
  { mk: "движење", en: "motion", phonetic: "", category: "words" },
  { mk: "течност", en: "liquid", phonetic: "", category: "words" },
  { mk: "се логирате", en: "log", phonetic: "", category: "words" },
  { mk: "значеше", en: "meant", phonetic: "", category: "words" },
  { mk: "количник", en: "quotient", phonetic: "", category: "words" },
  { mk: "заби", en: "teeth", phonetic: "", category: "words" },
  { mk: "школка", en: "shell", phonetic: "", category: "words" },
  { mk: "вратот", en: "neck", phonetic: "", category: "words" },
  { mk: "кислород", en: "oxygen", phonetic: "", category: "words" },
  { mk: "прилично", en: "pretty", phonetic: "", category: "words" },
  { mk: "вештина", en: "skill", phonetic: "", category: "words" },
  { mk: "жени", en: "women", phonetic: "", category: "words" },
  { mk: "сезона", en: "season", phonetic: "", category: "words" },
  { mk: "магнет", en: "magnet", phonetic: "", category: "words" },
  { mk: "гранка", en: "branch", phonetic: "", category: "words" },
  { mk: "натпревар", en: "match", phonetic: "", category: "words" },
  { mk: "суфиксот", en: "suffix", phonetic: "", category: "words" },
  { mk: "особено", en: "especially", phonetic: "", category: "words" },
  { mk: "огромен", en: "huge", phonetic: "", category: "words" },
  { mk: "челик", en: "steel", phonetic: "", category: "words" },
  { mk: "напред", en: "forward", phonetic: "", category: "words" },
  { mk: "слични", en: "similar", phonetic: "", category: "words" },
  { mk: "водење на", en: "guide", phonetic: "", category: "words" },
  { mk: "купи", en: "bought", phonetic: "", category: "words" },
  { mk: "теренот", en: "pitch", phonetic: "", category: "words" },
  { mk: "капут", en: "coat", phonetic: "", category: "words" },
  { mk: "картичка", en: "card", phonetic: "", category: "words" },
  { mk: "бендот", en: "band", phonetic: "", category: "words" },
  { mk: "јаже", en: "rope", phonetic: "", category: "words" },
  { mk: "се лизга", en: "slip", phonetic: "", category: "words" },
  { mk: "победа", en: "win", phonetic: "", category: "words" },
  { mk: "вечерта", en: "evening", phonetic: "", category: "words" },
  { mk: "алатка", en: "tool", phonetic: "", category: "words" },
  { mk: "Вкупно", en: "total", phonetic: "", category: "words" },
  { mk: "основните", en: "basic", phonetic: "", category: "words" },
  { mk: "мирисот", en: "smell", phonetic: "", category: "words" },
  { mk: "долина", en: "valley", phonetic: "", category: "words" },
  { mk: "ниту пак", en: "nor", phonetic: "", category: "words" },
  { mk: "двојно", en: "double", phonetic: "", category: "words" },
  { mk: "седиште", en: "seat", phonetic: "", category: "words" },
  { mk: "продолжи", en: "continue", phonetic: "", category: "words" },
  { mk: "блок", en: "block", phonetic: "", category: "words" },
  { mk: "шема", en: "chart", phonetic: "", category: "words" },
  { mk: "шапка", en: "hat", phonetic: "", category: "words" },
  { mk: "продаде", en: "sell", phonetic: "", category: "words" },
  { mk: "компанијата", en: "company", phonetic: "", category: "words" },
  { mk: "одземе", en: "subtract", phonetic: "", category: "words" },
  { mk: "настанот", en: "event", phonetic: "", category: "words" },
  { mk: "договор", en: "deal", phonetic: "", category: "words" },
  { mk: "пливање", en: "swim", phonetic: "", category: "words" },
  { mk: "терминот", en: "term", phonetic: "", category: "words" },
  { mk: "спротивно", en: "opposite", phonetic: "", category: "words" },
  { mk: "сопруга", en: "wife", phonetic: "", category: "words" },
  { mk: "чевли", en: "shoe", phonetic: "", category: "words" },
  { mk: "шири", en: "spread", phonetic: "", category: "words" },
  { mk: "организира", en: "arrange", phonetic: "", category: "words" },
  { mk: "камп", en: "camp", phonetic: "", category: "words" },
  { mk: "памук", en: "cotton", phonetic: "", category: "words" },
  { mk: "Роден", en: "born", phonetic: "", category: "words" },
  { mk: "кварта", en: "quart", phonetic: "", category: "words" },
  { mk: "камион", en: "truck", phonetic: "", category: "words" },
  { mk: "бучава", en: "noise", phonetic: "", category: "words" },
  { mk: "ниво", en: "level", phonetic: "", category: "words" },
  { mk: "шанса", en: "chance", phonetic: "", category: "words" },
  { mk: "се водат", en: "stretch", phonetic: "", category: "words" },
  { mk: "сјај", en: "shine", phonetic: "", category: "words" },
  { mk: "сопственост", en: "property", phonetic: "", category: "words" },
  { mk: "колона", en: "column", phonetic: "", category: "words" },
  { mk: "молекула", en: "molecule", phonetic: "", category: "words" },
  { mk: "сива", en: "gray", phonetic: "", category: "words" },
  { mk: "повторување", en: "repeat", phonetic: "", category: "words" },
  { mk: "носот", en: "nose", phonetic: "", category: "words" },
  { mk: "множина", en: "plural", phonetic: "", category: "words" },
  { mk: "барање", en: "claim", phonetic: "", category: "words" },
  { mk: "континент", en: "continent", phonetic: "", category: "words" },
];
